bot:
  name: FinePlaceBot
  token: 1658052423:AAFTM8X9cQF_uyqe3nyE5zeKcwgLqrJZ_1g
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourist_guide?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

message-to-user:
  city-is-not-in-the-database: К сожелению, я ничего не знаю об интересных местах в этом городе.

server-message: Successfully!